// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoFinalApi.Data;

#nullable disable

namespace ProjetoFinalApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoFinalApi.Locacao.Models.LocacaoApi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtSituacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLocador")
                        .HasColumnType("int");

                    b.Property<int>("IdPropostaLocador")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioSituacao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_LOCACOES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 0,
                            DtFim = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtSituacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLocador = 0,
                            IdPropostaLocador = 0,
                            IdUsuario = 1,
                            IdUsuarioSituacao = 0,
                            Nome = "Anual",
                            Situacao = "\0",
                            Valor = 150
                        },
                        new
                        {
                            Id = 2,
                            Classe = 0,
                            DtFim = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtSituacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLocador = 0,
                            IdPropostaLocador = 0,
                            IdUsuario = 2,
                            IdUsuarioSituacao = 0,
                            Nome = "Mensal",
                            Situacao = "\0",
                            Valor = 15
                        },
                        new
                        {
                            Id = 3,
                            Classe = 0,
                            DtFim = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtSituacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdLocador = 0,
                            IdPropostaLocador = 0,
                            IdUsuario = 3,
                            IdUsuarioSituacao = 0,
                            Nome = "Diario",
                            Situacao = "\0",
                            Valor = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
